//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WafTraffic.Applications.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WafTraffic.Applications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1}
        /// 
        ///This software is a reference sample of the WPF Application Framework (WAF).
        /// 
        ///http://waf.codeplex.com 的本地化字符串。
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Email cannot be created. Please correct the email address first. 的本地化字符串。
        /// </summary>
        internal static string CorrectEmailAddress {
            get {
                return ResourceManager.GetString("CorrectEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to close the application and lose the changes you made? 的本地化字符串。
        /// </summary>
        internal static string LoseChangesQuestion {
            get {
                return ResourceManager.GetString("LoseChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not available. 的本地化字符串。
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save the changes? 的本地化字符串。
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save operation was cancelled because of input errors. Please correct the error(s):
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string SaveErrorInvalidEntities {
            get {
                return ResourceManager.GetString("SaveErrorInvalidEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save operation was cancelled because some of the values are invalid. Please correct the field:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string SaveErrorInvalidFields {
            get {
                return ResourceManager.GetString("SaveErrorInvalidFields", resourceCulture);
            }
        }
    }
}
