//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WafTraffic.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WafTraffic.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _About... 的本地化字符串。
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Add 的本地化字符串。
        /// </summary>
        internal static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address book 的本地化字符串。
        /// </summary>
        internal static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Book library 的本地化字符串。
        /// </summary>
        internal static string BookLibrary {
            get {
                return ResourceManager.GetString("BookLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Book: {0} 的本地化字符串。
        /// </summary>
        internal static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+A 的本地化字符串。
        /// </summary>
        internal static string ControlA {
            get {
                return ResourceManager.GetString("ControlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+C 的本地化字符串。
        /// </summary>
        internal static string ControlC {
            get {
                return ResourceManager.GetString("ControlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+S 的本地化字符串。
        /// </summary>
        internal static string ControlS {
            get {
                return ResourceManager.GetString("ControlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+V 的本地化字符串。
        /// </summary>
        internal static string ControlV {
            get {
                return ResourceManager.GetString("ControlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+X 的本地化字符串。
        /// </summary>
        internal static string ControlX {
            get {
                return ResourceManager.GetString("ControlX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Y 的本地化字符串。
        /// </summary>
        internal static string ControlY {
            get {
                return ResourceManager.GetString("ControlY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+Z 的本地化字符串。
        /// </summary>
        internal static string ControlZ {
            get {
                return ResourceManager.GetString("ControlZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Copy 的本地化字符串。
        /// </summary>
        internal static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Email cannot be created. Please check that an email software is installed and configured. 的本地化字符串。
        /// </summary>
        internal static string CreateEmailError {
            get {
                return ResourceManager.GetString("CreateEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cu_t 的本地化字符串。
        /// </summary>
        internal static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database: {0} 的本地化字符串。
        /// </summary>
        internal static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Data 的本地化字符串。
        /// </summary>
        internal static string DataMenu {
            get {
                return ResourceManager.GetString("DataMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Del 的本地化字符串。
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Edit 的本地化字符串。
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_xit 的本地化字符串。
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap expired_picture {
            get {
                object obj = ResourceManager.GetObject("expired_picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 F1 的本地化字符串。
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firstname 的本地化字符串。
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First_name 的本地化字符串。
        /// </summary>
        internal static string FirstnameMenu {
            get {
                return ResourceManager.GetString("FirstnameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISBN 的本地化字符串。
        /// </summary>
        internal static string Isbn {
            get {
                return ResourceManager.GetString("Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lastname 的本地化字符串。
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lend to 的本地化字符串。
        /// </summary>
        internal static string LendTo {
            get {
                return ResourceManager.GetString("LendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lend to: 的本地化字符串。
        /// </summary>
        internal static string LendToCheck {
            get {
                return ResourceManager.GetString("LendToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        internal static string MoreButton {
            get {
                return ResourceManager.GetString("MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New email message. 的本地化字符串。
        /// </summary>
        internal static string NewEmailMessage {
            get {
                return ResourceManager.GetString("NewEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pages 的本地化字符串。
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Paste 的本地化字符串。
        /// </summary>
        internal static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish date 的本地化字符串。
        /// </summary>
        internal static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publisher 的本地化字符串。
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Redo 的本地化字符串。
        /// </summary>
        internal static string RedoMenu {
            get {
                return ResourceManager.GetString("RedoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Remove 的本地化字符串。
        /// </summary>
        internal static string RemoveMenu {
            get {
                return ResourceManager.GetString("RemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reporting 的本地化字符串。
        /// </summary>
        internal static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        internal static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Search 的本地化字符串。
        /// </summary>
        internal static string SearchMenu {
            get {
                return ResourceManager.GetString("SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select _all 的本地化字符串。
        /// </summary>
        internal static string SelectAllMenu {
            get {
                return ResourceManager.GetString("SelectAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spanish 的本地化字符串。
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Title 的本地化字符串。
        /// </summary>
        internal static string TitleMenu {
            get {
                return ResourceManager.GetString("TitleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Undo 的本地化字符串。
        /// </summary>
        internal static string UndoMenu {
            get {
                return ResourceManager.GetString("UndoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown application error
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Was returned 的本地化字符串。
        /// </summary>
        internal static string WasReturnedCheck {
            get {
                return ResourceManager.GetString("WasReturnedCheck", resourceCulture);
            }
        }
    }
}
