//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WafTraffic.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WafTraffic.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Author is mandatory. 的本地化字符串。
        /// </summary>
        internal static string AuthorMandatory {
            get {
                return ResourceManager.GetString("AuthorMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string AuthorMaxLength {
            get {
                return ResourceManager.GetString("AuthorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} by {1} 的本地化字符串。
        /// </summary>
        internal static string BookToString {
            get {
                return ResourceManager.GetString("BookToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided email address is invalid. 的本地化字符串。
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}
        ///{1}
        /// 的本地化字符串。
        /// </summary>
        internal static string EntityInvalid {
            get {
                return ResourceManager.GetString("EntityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firstname is mandatory. 的本地化字符串。
        /// </summary>
        internal static string FirstnameMandatory {
            get {
                return ResourceManager.GetString("FirstnameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firstname can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string FirstnameMaxLength {
            get {
                return ResourceManager.GetString("FirstnameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isbn can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string IsbnMaxLength {
            get {
                return ResourceManager.GetString("IsbnMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lastname is mandatory. 的本地化字符串。
        /// </summary>
        internal static string LastnameMandatory {
            get {
                return ResourceManager.GetString("LastnameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lastname can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string LastnameMaxLength {
            get {
                return ResourceManager.GetString("LastnameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pages must be equal or larger than {1}. 的本地化字符串。
        /// </summary>
        internal static string PagesEqualOrLarger {
            get {
                return ResourceManager.GetString("PagesEqualOrLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 的本地化字符串。
        /// </summary>
        internal static string PersonToString {
            get {
                return ResourceManager.GetString("PersonToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publisher can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string PublisherMaxLength {
            get {
                return ResourceManager.GetString("PublisherMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title is mandatory. 的本地化字符串。
        /// </summary>
        internal static string TitleMandatory {
            get {
                return ResourceManager.GetString("TitleMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title can contain {1} characters at maximum. 的本地化字符串。
        /// </summary>
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
    }
}
