use yctrafficdb 
go 

if exists(select * from sysobjects where name='PersonArchiveTable') drop table PersonArchiveTable
go 

create table PersonArchiveTable
(
	Id  					int not null primary key identity(1,1),
	PoliceTypeId			int,
	PoliceType				nvarchar(20),
	Name					nvarchar(20),
	Sex						nvarchar(2),
	Birthday				datetime,
	CarNumber				nvarchar(20),
	DepartmentId			int,
	DepartmentCode			nvarchar(20),
	DepartmentName			nvarchar(20),
	PoliticalId				int,
	Political				nvarchar(20),
	PartyTime				Datetime,
	EducationId				int,
	Education				nvarchar(20),
	Graduation				nvarchar(55),
	WorkTime				Datetime,
	PoliceTime				Datetime,
	Native					nvarchar(55),
	HomeLocation			nvarchar(55),
	PoliceNo				nvarchar(20),
	PoliceTitleId			int,
	PoliceTitle				nvarchar(20),
	LinkMethod				nvarchar(35),
	CardNo					nvarchar(50),
	Resume					nvarchar(505),
	HumanRelation			nvarchar(305),
	JobTitle				nvarchar(30),
	RetireTime				nvarchar(30),
	Motto					nvarchar(50),
	EduBackground			nvarchar(100),
	DegreeInfo				nvarchar(100),
	WorkResume				nvarchar(200),
	CommendInfo				nvarchar(200),
	HealthInfo				nvarchar(200),
	CommentMark				nvarchar(205),
	CreateUserId			int,
	CreateUserName			nvarchar(20),
	CreateTime				datetime, 	
	UpdaterId				int,
	UpdaterName				nvarchar(20),	
	UpdateTime				datetime,
	ApproverId				int,
	ApproverName				nvarchar(20),	
	ApproveTime				datetime,
	IntSpare1				int,
	IntSpare2				int,
	StrSpare1				nvarchar(31),
	StrSpare2				nvarchar(31),
	IsDeleted				bit NOT NULL DEFAULT 0,
)
